steps:
  # Step 1: Build the Python package (unchanged)
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip build
        python -m build

  # Step 2: Build a Docker image containing the package
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/python-build-artifact/my-python-package:latest'
      - '.'

  # Step 3: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/python-build-artifact/my-python-package:latest'

options:
  logging: CLOUD_LOGGING_ONLY
