steps:
  # Step 1: Install dependencies and build
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m pip install --upgrade pip build
        python -m build

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/python-build-artifact/myapp:$BUILD_ID'
      - '.'

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/python-build-artifact/myapp:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY