steps:
  # Step 1: Build the Python package (unchanged)
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip build
        python -m build

  # Step 2: Upload the build to Google Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Configure environment
        gcloud config set project $PROJECT_ID
        gcloud auth configure-docker us-central1-docker.pkg.dev

        # Upload the package to Google Artifact Registry
        gcloud artifacts packages upload python-build-artifact \
          --location=us-central1 \
          --repository=python-build-artifact \
          --package=my-python-package \
          --source=dist/*

options:
  logging: CLOUD_LOGGING_ONLY
