steps:
  # Step 1: Build the Python package (unchanged)
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip build twine
        python -m build

  # Step 2: Upload to Artifact Registry (fixed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Use Python 3 explicitly
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install twine

        # Authentication & configuration
        gcloud config set project $PROJECT_ID
        gcloud artifacts print-settings python \
          --repository=python-build-artifact \
          --location=us-central1 > ~/.pypirc

        # Upload package
        venv/bin/twine upload --repository python-build-artifact dist/*

options:
  logging: CLOUD_LOGGING_ONLY