steps:
  # Step 1: Build the package
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip build twine
        python -m build

  # Step 2: Upload to Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate using Cloud Build's default service account
        gcloud auth list  # Verify authentication
        gcloud config set project $PROJECT_ID

        # Configure Python repository
        gcloud artifacts print-settings python \
          --repository=python-build-artifact \
          --location=us-central1 > ~/.pypirc

        # Install twine in THIS container
        pip install twine

        # Upload package
        twine upload --repository python-build-artifact dist/*