steps:
  # Step 1: Install build tools globally
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m pip install --upgrade pip
        pip install build twine

  # Step 2: Build the package
  - name: 'python'
    entrypoint: 'python'
    args: ['-m', 'build']

  # Step 3: Configure Artifact Registry auth
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=$_SERVICE_ACCOUNT_KEY
        gcloud config set artifacts/repository python-build-artifact
        gcloud config set artifacts/location us-central1

  # Step 4: Upload to Artifact Registry
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        twine upload --repository-url https://us-central1-python.pkg.dev/$PROJECT_ID/python-build-artifact/ dist/*
        
options:
  logging: CLOUD_LOGGING_ONLY