steps:
  # Step 1: Build Python package
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m pip install --upgrade pip build
        python -m build

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/python-app-454407/python-docker/myapp:$BUILD_ID'
      - '.'

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/python-app-454407/python-docker/myapp:$BUILD_ID'



options:
  logging: CLOUD_LOGGING_ONLY