steps:
  # Step 1: Install build tools in the same container
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m pip install --upgrade pip
        pip install build twine
        python -m build

  # Step 2: Authenticate and configure Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=$_SERVICE_ACCOUNT_KEY
        gcloud artifacts print-settings python \
          --repository=python-build-artifact \
          --location=us-central1 > ~/.pypirc

  # Step 3: Upload package
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        twine upload --repository python-build-artifact dist/*

options:
  logging: CLOUD_LOGGING_ONLY