steps:
  # Step 1: Build the Python package (unchanged)
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip build twine
        python -m build

  # Step 2: Simplified upload using system Python 3
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ensure Python 3 and pip are available
        apt-get update && apt-get install -y python3-pip

        # Install twine directly in the container
        pip3 install --upgrade twine

        # Configure environment
        gcloud config set project $PROJECT_ID
        gcloud artifacts print-settings python \
          --repository=python-build-artifact \
          --location=us-central1 > ~/.pypirc

        # Upload using Python 3 module syntax
        python3 -m twine upload --repository python-build-artifact dist/*
options:
  logging: CLOUD_LOGGING_ONLY